### ISSUE TITLE
should _WD_WaitElement be used instead of _WD_FindElement ?

### ISSUE THREAD

**Issue by mlipok** [Danp2/au3WebDriver#357]
### Describe the bug

I was thinking about your statement:
`When I made the statement "You can't interact with an element if is isn't visible", I was speaking in general terms from the Webdriver specs.` from here:
https://www.autoitscript.com/forum/topic/205553-webdriver-udf-help-support-iii/?do=findComment&comment=1505364

and I start to wonder why `_WD_LinkClickByText` is using `_WD_FindElement` instead `_WD_WaitElement` ?

### Expected behavior

If webdriver is not able do interact with an elemement that is not visible then why we are not demanding it in function like `_WD_FindElement` ?

### Additional context
https://www.autoitscript.com/forum/topic/205553-webdriver-udf-help-support-iii/?do=findComment&comment=1505364

### System under test

not related

**Comment by Danp2** [comment]
> should _WD_WaitElement be used instead of _WD_FindElement ? 

My two cents worth --

- Some functions like _WD_LinkClickByText likely existed before _WD_WaitElement was added
- _WD_WaitElement is intended to be used as a way to ensure the page is fully loaded beyond the basic checks performed by _WD_Loadwait
- There are times (the situation you linked above is one) where using _WD_WaitElement wouldn't improve the situation and would only delay the end result where an error will be generated because the element isn't visible. 

Therefore, I'm of the opinion that the answer to your question is "no".

> If webdriver is not able do interact with an elemement that is not visible then why we are not demanding it in function like _WD_FindElement ?

Because _WD_FindElement is intended to implement the [this portion](https://www.w3.org/TR/webdriver/#element-retrieval) of the W3C specs. Nothing more, nothing less. 😉 

If you want something else, it would need to go into a different function in wd_helper.

**Comment by mlipok** [comment]
Thanks for you answer.

Ok I understand the case this way:

So we do not need to try to add some more checking in `_WD_LinkClickByText` just leaving it to WebDriver and then we get error because... 
In another way you will ask me: Why we should check them to return another kind of error ?

I'm I right ?

**Comment by Danp2** [comment]
> Why we should check them to return another kind of error ?

True... there's no point in performing the additional check(s) (which would mean making additional calls to the webdriver) if we can rely on the Webdriver to detect the issue and return an error.

However, this discussion has highlighted a separate issue for me. Currently _WD_LinkClickByText only locates and clicks on the first matching link. What if there are multiple matches and the first link isn't clickable? This would generate an error because the click attempt failed.

_WD_LinkClickByText could be improved by checking for multiple matching links and looping through them until a clickable one is located.

**Comment by mlipok** [comment]
So feel free to close this issue and open new one ;)
