### ISSUE TITLE
Review / fix the verbiage of URL option

### ISSUE THREAD

**Issue by Danp2** [Danp2/au3WebDriver#523]
https://github.com/Danp2/au3WebDriver/blob/master/wd_core.au3#L503

**Comment by Sven-Seyfert** [comment]
To be honest, I don't get it.

> URL - Protocol binding to load the URL of the browser. If a baseUrl is specified in the config, it will be prepended to the url parameter. Calling this function with the same url as last time will trigger a page reload

I don't see any reload mechanism in case of the same url is used again.

The [WebDriver docs](https://www.w3.org/TR/webdriver/#get-current-url) say this:

> The Get Current URL command returns the URL of the current top-level browsing context.

----------

My suggestion is, in case I have not missed something, simplyfy the description like for the title "returns the document title of the current top-level browsing context" to something like "returns the document title of the current top-level browsing context".
Otherwise leave it as it is, because the user don't care, to be honest. 

Is this helpful in any way 🤔 ?

@Danp2
@mlipok 

Best regards
Sven

**Comment by Danp2** [comment]
@Sven-Seyfert Yes... I created this issue because the description appeared incorrect.

**Comment by Sven-Seyfert** [comment]
If you want I can adjust this small thingy and setup a PR, @Danp2 . But in either way, I think this is and should not be a show-stopper for a new release (v1.4.0), right?
